@hostname = http://127.0.0.1
@port = 8000
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}/api
@contentType = application/json


### GET all ourse details
GET {{baseUrl}}/course-api

### GET ourse details using id
GET {{baseUrl}}/course-api?id=1

### Add new Course
POST {{baseUrl}}/course-api
content-type: {{contentType}}

{
    "cors_cat": "Diploma course",
    "cors_name": "DCA",
    "cors_full": "Diploma in computer application",
    "cors_dur": "3",
    "cors_detail": "This is the DCA couse full form is Diploma in computer application",
    "cors_pack": "2000"
}

### Update Course
PUT {{baseUrl}}/course-api?id=1
content-type: {{contentType}}

{
    "cors_cat": "Diploma course",
    "cors_name": "CCC",
    "cors_full": "Course on computer concept",
    "cors_dur": "3",
    "cors_detail": "This is the CCC couse full form is Course on computer concept",
    "cors_pack": "3000"
}

### Delete the Course
DELETE {{baseUrl}}/course-api?id=16



### Get all data of student
GET {{baseUrl}}/student-api

### Get specific data of student
GET {{baseUrl}}/student-api?id=1