@hostname = http://127.0.0.1
@port = 8000
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}/api
@contentType = application/json


### GET all ourse details
GET {{baseUrl}}/course-api

### GET ourse details using id
GET {{baseUrl}}/course-api?id=7423570f-40b8-4399-8917-592b1cfddd74

### Add new Course
POST {{baseUrl}}/course-api
content-type: {{contentType}}

{
    "course_category": "Diploma course",
    "course_name": "DCA",
    "course_full_form": "Diploma in computer application",
    "course_duration": "3",
    "course_detail": "This is the DCA couse full form is Diploma in computer application",
    "course_package": "2000"
}

### Update Course
PUT {{baseUrl}}/course-api?id=7423570f-40b8-4399-8917-592b1cfddd74
content-type: {{contentType}}

{
    "course_category": "Diploma course",
    "course_name": "CCC",
    "course_full_form": "Course on computer concept",
    "course_duration": "3",
    "course_detail": "This is the CCC couse full form is Course on computer concept",
    "course_package": "3000"
}

### Delete the Course
DELETE {{baseUrl}}/course-api?id=7423570f-40b8-4399-8917-592b1cfddd74



### Get all data of student
GET {{baseUrl}}/student-api

### Get specific data of student
GET {{baseUrl}}/student-api?id=425d5165-01f9-4354-ad05-12c1ada8c7f0

### Add new Course
POST {{baseUrl}}/student-api
content-type: {{contentType}}

{
    "name" : "Test",
    "gender" : "Test",
    "father" : "Test",
    "mother" : "Test",
    "dob" : "2021-01-23",
    "address" : "Test",
    "contact" : "Test",
    "category" : "Test",
    "course" : "3",
    "lpc" : "Test",
    "passing_year" : "2021",
    "board" : "Test",
    "gread" : "Test"
}

### Update Course
PUT {{baseUrl}}/student-api?id=1
content-type: {{contentType}}

{
    "name": "Rahul patel",
    "gender": "Male",
    "father": "Rohan patel",
    "mother": "Radha patel",
    "dob": "2022-01-21",
    "address": "Rampur varanasi",
    "contact": "8090607080",
    "category": "OBC",
    "course": 3,
    "lpc": "BSc",
    "passing_year": "2021",
    "board": "MGKVP",
    "gread": "First class"
}

### Delete the Student
DELETE {{baseUrl}}/student-api?id=4