version: '3'

services:
  cims-local:
    build:
      context: .
      dockerfile: ./config/local/Dockerfile
    image: abhay4122/cims:dev
    container_name: cims-django
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    ports:
      - '8080:8000'
