# Generated by Django 3.2.7 on 2022-01-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cors_cat', models.CharField(max_length=100)),
                ('cors_name', models.CharField(max_length=100)),
                ('cors_full', models.CharField(max_length=150)),
                ('cors_dur', models.CharField(max_length=20)),
                ('cors_detail', models.CharField(max_length=250)),
                ('cors_pack', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('father', models.CharField(max_length=150)),
                ('mother', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=25)),
                ('lpc', models.CharField(max_length=50)),
                ('passing_year', models.CharField(max_length=10)),
                ('board', models.CharField(max_length=100)),
                ('gread', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='edu/images')),
                ('reg_year', models.CharField(max_length=10)),
                ('reg_mon', models.CharField(max_length=10)),
                ('session_year', models.CharField(max_length=10)),
                ('session_month', models.CharField(max_length=10)),
                ('dor', models.DateField(auto_now_add=True)),
                ('enroll_number', models.CharField(max_length=50)),
                ('cretificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('theory_s1', models.CharField(blank=True, max_length=100, null=True)),
                ('os_s1', models.CharField(blank=True, max_length=100, null=True)),
                ('pretical_s1', models.CharField(blank=True, max_length=100, null=True)),
                ('theory_s2', models.CharField(blank=True, max_length=100, null=True)),
                ('pretical_s2', models.CharField(blank=True, max_length=100, null=True)),
                ('oral_s2', models.CharField(blank=True, max_length=100, null=True)),
                ('is_registerd', models.BooleanField(default=False)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('is_examinee', models.BooleanField(default=False)),
                ('is_certified', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapi.course')),
            ],
        ),
    ]
