# Generated by Django 3.2.7 on 2022-02-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cors_cat',
            new_name='course_category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cors_dur',
            new_name='course_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cors_full',
            new_name='course_full_form',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cors_name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cors_pack',
            new_name='course_package',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cors_detail',
        ),
        migrations.AddField(
            model_name='course',
            name='course_detail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eduapi.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_mon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
